const fs = require('fs');
const path = require('path');
const { svgPathBbox: bbox } = require('svg-path-bbox');

const SVG_DIR = path.resolve(__dirname, '..', 'node_modules/@phosphor-icons/core/assets/regular');
const OUT = path.resolve(__dirname, '..', 'src/icons/registry.ts');

const files = fs.readdirSync(SVG_DIR).filter(f => f.endsWith('.svg'));
const registry = {};

for (const file of files) {
  const name = file.replace('.svg', '');
  const svg = fs.readFileSync(path.join(SVG_DIR, file), 'utf-8');

  const dMatch = svg.match(/<path\s+d="([^"]+)"/);
  if (!dMatch) continue;
  const d = dMatch[1];

  // Tight bounding box [minX, minY, maxX, maxY]
  let box;
  try {
    box = bbox(d);
  } catch {
    // fallback to full 256x256 viewBox if bbox fails
    box = [0, 0, 256, 256];
  }

  const [minX, minY, maxX, maxY] = box;
  const w = maxX - minX;
  const h = maxY - minY;

  registry[name] = { v: `${Math.round(minX)} ${Math.round(minY)} ${Math.round(w)} ${Math.round(h)}`, d };
}

const code = `// Auto-generated by scripts/build-icons.js — do not edit manually

export interface IconRecord {
  v: string;
  d: string;
}

export const icons: Record<string, IconRecord> = ${JSON.stringify(registry, null, 2)};
`;

fs.writeFileSync(OUT, code, 'utf-8');
console.log(`Built ${Object.keys(registry).length} icons → ${OUT}`);
